# Generated by Django 5.1.3 on 2024-12-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_loginform'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('date', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='loginform',
            name='fullname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='loginform',
            name='password1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='loginform',
            name='password2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
